// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgyQoaazC7mgk-y5xFKjnXUClA3kSg_0Y',
    appId: '1:950141044596:web:53ba748a773f347e100e21',
    messagingSenderId: '950141044596',
    projectId: 'shoe-store-f8995',
    authDomain: 'shoe-store-f8995.firebaseapp.com',
    storageBucket: 'shoe-store-f8995.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDulD2pG66sfajBsmZs04JarOXAaV_-JM0',
    appId: '1:950141044596:android:3db14b0976d8543c100e21',
    messagingSenderId: '950141044596',
    projectId: 'shoe-store-f8995',
    storageBucket: 'shoe-store-f8995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrkCclRtG_1a_TddeRtNkSAGngisSUrA',
    appId: '1:950141044596:ios:c4e14f1377d5b0d1100e21',
    messagingSenderId: '950141044596',
    projectId: 'shoe-store-f8995',
    storageBucket: 'shoe-store-f8995.appspot.com',
    iosClientId: '950141044596-ta5hgs3sq6arb30lec4gta48g5gell1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrkCclRtG_1a_TddeRtNkSAGngisSUrA',
    appId: '1:950141044596:ios:d42a2725ad9341fd100e21',
    messagingSenderId: '950141044596',
    projectId: 'shoe-store-f8995',
    storageBucket: 'shoe-store-f8995.appspot.com',
    iosClientId: '950141044596-r751drtl7re40ccq1g91llsd3cdo20at.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectify.RunnerTests',
  );
}
